FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del middleware y protocolo
COPY middleware/ ./middleware/
COPY protocol/ ./protocol/

# Copiar el script de prueba
COPY scripts/queue1on1/test_producer.py .

# Variables de entorno por defecto
ENV RABBITMQ_HOST=rabbitmq
ENV QUEUE_NAME=test_queue_1to1

# Comando por defecto
CMD ["python3", "test_producer.py"]
