services:
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - middleware-network

  consumer:
    build:
      context: ../../
      dockerfile: scripts/queue1on1/Dockerfile.consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: test_queue_1to1
    networks:
      - middleware-network
    restart: "no"

  producer:
    build:
      context: ../../
      dockerfile: scripts/queue1on1/Dockerfile.producer
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: test_queue_1to1
    networks:
      - middleware-network
    restart: "no"

networks:
  middleware-network:
    driver: bridge
